name: gestor_lds
description: "Proyecto de gestion de reuniones y agendas"
publish_to: 'none'

# CAMBIO 1: Actualizamos versión para el despliegue
version: 1.7.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # DEPENDENCIAS DE FIREBASE
  firebase_core: ^2.27.2
  firebase_auth: ^4.17.2
  cloud_firestore: ^4.15.8
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  pdf: ^3.10.6
  printing: ^5.11.1
  package_info_plus: ^9.0.0
  table_calendar: ^3.2.0
  provider: ^6.1.5+1
  url_launcher: ^6.2.0
  add_2_calendar: ^3.0.1
  # FIN DE DEPENDENCIAS

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  # CAMBIO 2: Agregamos el paquete de Splash
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0

# Configuración de Iconos (Ya la tenías)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#164772"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#164772"
    theme_color: "#164772"

# CAMBIO 3: Configuración del Splash Screen (ATHEM DevWorks)
flutter_native_splash:
  color: "#FFFFFF" # Fondo Blanco Limpio
  image: assets/images/logo_athem_devworks.png # <--- TU LOGO AQUÍ

  # Configuración WEB (Importante para tu despliegue)
  web: true

  # Configuración Android/iOS
  android: true
  ios: true
  android_12:
    image: assets/images/logo_athem_devworks.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logont.png
    # Asegúrate de registrar el nuevo logo también para usarlo en el "Acerca de"
    - assets/images/logo_athem_devworks.png