name: gestor_lds
description: "Proyecto de gestion de reuniones y agendas"
publish_to: 'none'

# CAMBIO 1: Actualizamos versión para el despliegue
version: 2.1.3+3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # DEPENDENCIAS DE FIREBASE
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  pdf: ^3.10.6
  printing: ^5.11.1
  package_info_plus: ^9.0.0
  table_calendar: ^3.2.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  add_2_calendar: ^3.0.1
  fl_chart: ^1.1.1
  flutter_svg: ^2.3.0
  # FIN DE DEPENDENCIAS

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  # CAMBIO 2: Agregamos el paquete de Splash
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

# Configuración de Iconos (Ya la tenías)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "#164772"
  adaptive_icon_foreground: "assets/icons/icon_launcher.png"
  web:
    generate: true
    image_path: "assets/icons/icon_launcher.png"
    background_color: "#164772"
    theme_color: "#164772"

# CAMBIO 3: Configuración del Splash Screen (ATHEM DevWorks)
flutter_native_splash:
  color: "#FFFFFF" # Fondo Blanco Limpio
  image: assets/images/logo_athem_devworks.png # <--- TU LOGO AQUÍ

  # Configuración WEB (Importante para tu despliegue)
  web: true

  # Configuración Android/iOS
  android: true
  ios: true
  android_12:
    image: assets/images/logo_athem_devworks.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/import_arevalo.json
    - assets/import_nuevo_trujillo.json