// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKYUtcs7G1QUJgenNyf9JH9DzPkKbrhE',
    appId: '1:352891071220:web:bab49e7d881bde0829cca1',
    messagingSenderId: '352891071220',
    projectId: 'gestorlds-demo',
    authDomain: 'gestorlds-demo.firebaseapp.com',
    storageBucket: 'gestorlds-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6b2VcdFDsGhoqGHe4Ak88gkK9dOrDkE',
    appId: '1:352891071220:android:3c75c370c71a272929cca1',
    messagingSenderId: '352891071220',
    projectId: 'gestorlds-demo',
    storageBucket: 'gestorlds-demo.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJePeiORCWDLuE9SNU7WSbcEGGvmfo-Jk',
    appId: '1:352891071220:ios:a22aac9a3db08cef29cca1',
    messagingSenderId: '352891071220',
    projectId: 'gestorlds-demo',
    storageBucket: 'gestorlds-demo.firebasestorage.app',
    iosBundleId: 'com.nuevotrujillo.gestorlds.gestorLds',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJePeiORCWDLuE9SNU7WSbcEGGvmfo-Jk',
    appId: '1:352891071220:ios:ca96f16c932bc92e29cca1',
    messagingSenderId: '352891071220',
    projectId: 'gestorlds-demo',
    storageBucket: 'gestorlds-demo.firebasestorage.app',
    iosBundleId: 'com.athemdevworks.gestorlds.estaca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvKYUtcs7G1QUJgenNyf9JH9DzPkKbrhE',
    appId: '1:352891071220:web:95729e0880e7a57129cca1',
    messagingSenderId: '352891071220',
    projectId: 'gestorlds-demo',
    authDomain: 'gestorlds-demo.firebaseapp.com',
    storageBucket: 'gestorlds-demo.firebasestorage.app',
  );
}
