// MAPA DE ORGANIZACIONES Y LLAMAMIENTOS
const Map<String, List<String>> kLdsStructure = {
  'Obispado': [
    'Obispo',
    'Primer Consejero del Obispado',
    'Segundo Consejero del Obispado',
    'Secretario de Barrio',
    'Secretario Ejecutivo de Barrio',
    'Secretario Auxiliar',
  ],
  'Cuórum de Élderes': [
    'Presidente del Cuórum de Élderes',
    'Primer Consejero del Cuórum de Élderes',
    'Segundo Consejero del Cuórum de Élderes',
    'Secretario del Cuórum de Élderes',
    'Secretario Auxiliar',
  ],
  'Sociedad de Socorro': [
    'Presidenta de la Sociedad de Socorro',
    'Primera Consejera de la Sociedad de Socorro',
    'Segunda Consejera de la Sociedad de Socorro',
    'Secretaria Auxiliar',
  ],
  'Sacerdocio Aarónico': [
    'Presidente del Cuórum de Diáconos',
    'Primer Consejero del Cuórum de Diáconos',
    'Segundo Consejero del Cuórum de Diáconos',
    'Secretario del Cuórum de Diáconos',
    'Asesor de Cuórum de Diáconos',
    'Presidente del Cuórum de Maestros',
    'Primer Consejero del Cuórum de Maestros',
    'Segundo Consejero del Cuórum de Maestros',
    'Secretario del Cuórum de Maestros',
    'Asesor del Cuórum de Maestros',
    'Primer Ayudante del Cuórum de Presbíteros',
    'Segundo Ayudante del Cuórum de Presbíteros',
    'Secretario del Cuórum de Presbíteros',
    'Asesor del Cuórum de Presbíteros',
  ],
  'Mujeres Jóvenes': [
    'Presidenta de las Mujeres Jóvenes',
    'Primera Consejera de las Mujeres Jóvenes',
    'Segunda Consejera de las Mujeres Jóvenes',
    'Secretaria de las Mujeres Jóvenes',
    'Lider de Actividades de las Mujeres Jóvenes',
    'Presidenta de la Clase de 11-14',
    'Primera Consejera de la Clase de 11-14',
    'Segunda Consejera de la Clase de 11-14',
    'Secretaria de la Clase de 11-14',
    'Asesora de la Clase de 11-14',
    'Presidenta de la Clase de 15-17',
    'Primera Consejera de la Clase de 15-17',
    'Segunda Consejera de la Clase de 15-17',
    'Secretaria de la Clase de 15-17',
    'Asesora de la Clase de 15-17',
  ],
  'Primaria': [
    'Presidenta de la Primaria',
    'Primera Consejera de la Primaria',
    'Segunda Consejera de la Primaria',
    'Secretaria de la Primaria',
    'Líder de Música de la Primaria',
    'Líder de Actividades de la Primaria',
  ],
  'Escuela Dominical': [
    'Presidente de la Escuela Dominical',
    'Primer Consejero de la Escuela Dominical',
    'Segundo Consejero de la Escuela Dominical',
    'Secretario de la Escuela Dominical',
    'Maestro de la Escuela Dominical',
  ],
  'Templo e Historia Familiar': [
    'Líder de Templo e Historia Familiar',
    'Consultor de Templo e Historia Familiar',
  ],
  'Misiones del Barrio': [
    'Líder Misional de Barrio',
    'Misionero de Barrio',
  ],
  'Joven Adulto Soltero':[
    'Asesora de la Sociedad de Socorro para las jóvenes adultas solteras',
    'Asesor de jóvenes adultos solteros',
    'Líder de los jóvenes adultos solteros',
    'Líder de los jóvenes adultos solteros',
    'Presidente del Comité de Jóvenes Adultos Solteros',
    'Miembro del Comité de Jóvenes Adultos Solteros',
  ],
  'Música': [
    'Pianista u organista del sacerdocio',
    'Director de música del sacerdocio',
    'Pianista de coro',
    'Asesor musical',
    'Director(a) de coro',
    'Pianista u organista',
    'Líder de música',
    'Coordinador de música',
      ],
  'Revistas': [
    'Representante de la revista Liahona',
  ],
  'Instalaciones': [
    'Representante del edificio',
    'Programador--Edificio 1',
    'Programador--Edificio 2',
    'Programador--Edificio 3',
    'Programador--Edificio 4',
    'Programador--Edificio 5',
  ],
  'Para la Fortaleza de la Juventud': [
    'Representante de FSY',
  ],
  'Historia': [
    'Especialista en historia',
  ],
  'Tecnología': [
    'Especialista en comunicación por correo electrónico',
    'Especialista en tecnología',
    'Intérprete de Barrio/Rama',
  ],
  'Bienestar y Autosuficiencia': [
    'Líder de actividades para personas con discapacidades',
    'Especialista en discapacidades',
    'Especialista en Bienestar y Autosuficiencia',
    'Facilitador de grupo de autosuficiencia'
  ]

};